INSERT INTO `chapter` VALUES (1, '扫描转换', 1, NULL);
INSERT INTO `chapter` VALUES (2, '几何变换', 1, NULL);
INSERT INTO `chapter` VALUES (3, '3D渲染管道', 1, NULL);
INSERT INTO `chapter` VALUES (4, '隐藏面消除', 1, NULL);
INSERT INTO `chapter` VALUES (5, 'Shading', 1, NULL);
INSERT INTO `chapter` VALUES (6, '纹理映射', 1, NULL);
INSERT INTO `chapter` VALUES (7, '光线跟踪', 1, NULL);
INSERT INTO `chapter` VALUES (8, '颜色与图像合成', 1, NULL);
INSERT INTO `chapter` VALUES (9, 'VR', 1, NULL);
INSERT INTO `chapter` VALUES (10, '物体表示', 1, NULL);
INSERT INTO `chapter` VALUES (36, '一、软件测试质量保障与软件测试基础', 3, NULL);
INSERT INTO `chapter` VALUES (37, '二、软件测试质量保障——需求工程简介', 3, NULL);
INSERT INTO `chapter` VALUES (38, '三、建模技术', 3, NULL);
INSERT INTO `chapter` VALUES (40, '四、软件测试基本过程', 3, NULL);
INSERT INTO `chapter` VALUES (41, '五、软件测试管理', 3, NULL);
INSERT INTO `chapter` VALUES (42, '六、黑盒测试用例设计技术', 3, NULL);
INSERT INTO `chapter` VALUES (43, '七、白盒测试用例设计技术', 3, NULL);
INSERT INTO `chapter` VALUES (45, '第一讲：软件过程概述', 23, NULL);
INSERT INTO `chapter` VALUES (47, '第二讲CMM和CMMI', 23, NULL);
INSERT INTO `chapter` VALUES (48, '第三、四讲 软件开发的演化本质与软件过程', 23, NULL);
INSERT INTO `chapter` VALUES (49, '第五、六讲 Scrum-通过实例介绍敏捷开发方法', 23, NULL);
INSERT INTO `chapter` VALUES (50, '第七讲 敏捷和精益方法概述', 23, NULL);
INSERT INTO `chapter` VALUES (51, '第八讲 产品愿景', 23, NULL);
INSERT INTO `chapter` VALUES (53, '第九讲 需求和用户故事', 23, NULL);
INSERT INTO `chapter` VALUES (54, '测试测试测试', 6, NULL);
